minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - prisma@7.10.0
  - semver@6.3.1
  - undici-types@6.21.0

shellEmulator: true

overrides:
  '@hono/node-server': ^1.19.14

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  workerd: true
