/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsSlugRouteImport } from './routes/_authed/groups/$slug'
import { Route as AuthedGroupsSlugIndexRouteImport } from './routes/_authed/groups/$slug/index'
import { Route as AuthedGroupsSlugSettingsRouteImport } from './routes/_authed/groups/$slug/settings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsSlugRoute = AuthedGroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsSlugIndexRoute = AuthedGroupsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsSlugRoute,
} as any)
const AuthedGroupsSlugSettingsRoute =
  AuthedGroupsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedGroupsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthedAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/groups/$slug': typeof AuthedGroupsSlugRouteWithChildren
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthedAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/groups/$slug': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/_authed/groups/$slug': typeof AuthedGroupsSlugRouteWithChildren
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/_authed/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/auth/callback'
    | '/auth/confirm'
    | '/groups/$slug'
    | '/groups/create'
    | '/groups/'
    | '/groups/$slug/settings'
    | '/groups/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/auth/callback'
    | '/auth/confirm'
    | '/groups/create'
    | '/groups'
    | '/groups/$slug/settings'
    | '/groups/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authed/account'
    | '/auth/callback'
    | '/auth/confirm'
    | '/_authed/groups/$slug'
    | '/_authed/groups/create'
    | '/_authed/groups/'
    | '/_authed/groups/$slug/settings'
    | '/_authed/groups/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$slug': {
      id: '/_authed/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof AuthedGroupsSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$slug/': {
      id: '/_authed/groups/$slug/'
      path: '/'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof AuthedGroupsSlugIndexRouteImport
      parentRoute: typeof AuthedGroupsSlugRoute
    }
    '/_authed/groups/$slug/settings': {
      id: '/_authed/groups/$slug/settings'
      path: '/settings'
      fullPath: '/groups/$slug/settings'
      preLoaderRoute: typeof AuthedGroupsSlugSettingsRouteImport
      parentRoute: typeof AuthedGroupsSlugRoute
    }
  }
}

interface AuthedGroupsSlugRouteChildren {
  AuthedGroupsSlugSettingsRoute: typeof AuthedGroupsSlugSettingsRoute
  AuthedGroupsSlugIndexRoute: typeof AuthedGroupsSlugIndexRoute
}

const AuthedGroupsSlugRouteChildren: AuthedGroupsSlugRouteChildren = {
  AuthedGroupsSlugSettingsRoute: AuthedGroupsSlugSettingsRoute,
  AuthedGroupsSlugIndexRoute: AuthedGroupsSlugIndexRoute,
}

const AuthedGroupsSlugRouteWithChildren =
  AuthedGroupsSlugRoute._addFileChildren(AuthedGroupsSlugRouteChildren)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedGroupsSlugRoute: typeof AuthedGroupsSlugRouteWithChildren
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedGroupsSlugRoute: AuthedGroupsSlugRouteWithChildren,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
