-- Rollout stage 1 persistent abuse controls and reconciliation state for privileged Auth
-- invitation provisioning. Raw recipient addresses are never stored.

set lock_timeout = '5s';
set statement_timeout = '60s';

create table public.invitation_security_event (
  id bigint generated by default as identity primary key,
  operation_id uuid not null,
  event_kind text not null check (event_kind in ('group_create', 'invitation')),
  actor_id uuid not null,
  group_id uuid,
  request_digest text not null check (request_digest ~ '^[0-9a-f]{64}$'),
  recipient_hash text check (recipient_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'reserved'
    check (status in ('reserved', 'auth_provisioned', 'membership_created', 'failed')),
  auth_user_id uuid,
  delivery_status text not null default 'not_attempted'
    check (delivery_status in ('not_attempted', 'existing', 'sent', 'unknown')),
  failure_stage text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (event_kind = 'group_create' and recipient_hash is null)
    or (event_kind = 'invitation' and recipient_hash is not null)
  ),
  check (status not in ('auth_provisioned', 'membership_created') or auth_user_id is not null or event_kind = 'group_create')
);

create unique index invitation_security_operation_recipient_unique
  on public.invitation_security_event (operation_id, recipient_hash)
  where event_kind = 'invitation';
create unique index invitation_security_group_create_operation_unique
  on public.invitation_security_event (operation_id)
  where event_kind = 'group_create';
create index invitation_security_actor_created_idx
  on public.invitation_security_event (actor_id, created_at desc);
create index invitation_security_group_created_idx
  on public.invitation_security_event (group_id, created_at desc)
  where group_id is not null and event_kind = 'invitation';
create index invitation_security_recipient_created_idx
  on public.invitation_security_event (recipient_hash, created_at desc)
  where recipient_hash is not null;
create index invitation_security_created_idx
  on public.invitation_security_event (created_at);
create index invitation_security_reconciliation_idx
  on public.invitation_security_event (status, updated_at)
  where status in ('reserved', 'auth_provisioned', 'failed');

alter table public.invitation_security_event enable row level security;
revoke all on table public.invitation_security_event from public, anon, authenticated, service_role;
revoke all on sequence public.invitation_security_event_id_seq from public, anon, authenticated, service_role;
grant select, insert, update on table public.invitation_security_event to pair_research_runtime;
grant usage on sequence public.invitation_security_event_id_seq to pair_research_runtime;

create policy pair_research_runtime_select on public.invitation_security_event
  for select to pair_research_runtime using (true);
create policy pair_research_runtime_insert on public.invitation_security_event
  for insert to pair_research_runtime with check (true);
create policy pair_research_runtime_update on public.invitation_security_event
  for update to pair_research_runtime using (true) with check (true);

comment on table public.invitation_security_event is
  'Hashed invitation rate counters and provisioning reconciliation ledger; retain 30 days and never expose through the Data API.';
